# Generated by Django 5.2.6 on 2026-09-20 18:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

from core.db.rls import ddl_tenant_context_operations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_client_business_profile'),
        ('documents', '0002_row_level_security'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        *ddl_tenant_context_operations(),
        migrations.CreateModel(
            name='GstRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('gstin_enc', models.BinaryField(blank=True, null=True)),
                ('gstin_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('state_code', models.CharField(max_length=2)),
                ('registration_type', models.CharField(choices=[('regular', 'Regular'), ('composition', 'Composition'), ('other', 'Other')], default='regular', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_registrations', to='core.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
            ],
            options={
                'db_table': 'gst_registration',
                'ordering': ['state_code', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('period_start', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('signed_off', 'Signed off')], default='draft', max_length=16)),
                ('signed_off_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_runs', to='core.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
                ('portal_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document')),
                ('register_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='gst.gstregistration')),
                ('signed_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gst_recon_run',
                'ordering': ['-period_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('match_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('kind', models.CharField(choices=[('accept_match', 'Accept as a match'), ('claim_itc', 'Claim the credit'), ('disallow_itc', 'Disallow the credit'), ('defer', 'Defer to a later month'), ('note', 'Note'), ('sign_off', 'Signed off the run')], max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='gst.reconrun')),
            ],
            options={
                'db_table': 'gst_recon_decision',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gstr2bInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('gstin_enc', models.BinaryField(blank=True, null=True)),
                ('gstin_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('invoice_no', models.CharField(max_length=64)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255)),
                ('hsn', models.CharField(blank=True, default='', max_length=16)),
                ('section', models.CharField(default='B2B', max_length=4)),
                ('taxable_paise', models.BigIntegerField(default=0)),
                ('igst_paise', models.BigIntegerField(default=0)),
                ('cgst_paise', models.BigIntegerField(default=0)),
                ('sgst_paise', models.BigIntegerField(default=0)),
                ('cess_paise', models.BigIntegerField(default=0)),
                ('source_row', models.PositiveIntegerField(default=0)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_rows', to='gst.reconrun')),
            ],
            options={
                'db_table': 'gst_gstr2b_invoice',
                'ordering': ['source_row'],
            },
        ),
        migrations.CreateModel(
            name='RegisterInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('gstin_enc', models.BinaryField(blank=True, null=True)),
                ('gstin_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('invoice_no', models.CharField(max_length=64)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255)),
                ('hsn', models.CharField(blank=True, default='', max_length=16)),
                ('section', models.CharField(default='B2B', max_length=4)),
                ('taxable_paise', models.BigIntegerField(default=0)),
                ('igst_paise', models.BigIntegerField(default=0)),
                ('cgst_paise', models.BigIntegerField(default=0)),
                ('sgst_paise', models.BigIntegerField(default=0)),
                ('cess_paise', models.BigIntegerField(default=0)),
                ('source_row', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, default='', max_length=128)),
                ('rcm', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_rows', to='gst.reconrun')),
            ],
            options={
                'db_table': 'gst_register_invoice',
                'ordering': ['source_row'],
            },
        ),
        migrations.CreateModel(
            name='ReconMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('kind', models.CharField(max_length=24)),
                ('itc_status', models.CharField(max_length=24)),
                ('eligible_paise', models.BigIntegerField(default=0)),
                ('ineligible_paise', models.BigIntegerField(default=0)),
                ('cause', models.TextField(blank=True, default='')),
                ('action', models.TextField(blank=True, default='')),
                ('differences', models.JSONField(blank=True, default=dict)),
                ('timing', models.BooleanField(default=False)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
                ('portal_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gst.gstr2binvoice')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='gst.reconrun')),
                ('register_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gst.registerinvoice')),
            ],
            options={
                'db_table': 'gst_recon_match',
                'ordering': ['kind', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='gstregistration',
            constraint=models.UniqueConstraint(fields=('firm', 'client', 'gstin_hash'), name='uniq_gst_registration_per_client'),
        ),
        migrations.AddConstraint(
            model_name='reconrun',
            constraint=models.UniqueConstraint(fields=('firm', 'registration', 'period_start'), name='uniq_gst_run_per_period'),
        ),
    ]
