# Generated by Django 5.2.6 on 2026-09-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0002_row_level_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstr2binvoice',
            name='itc_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gstr2binvoice',
            name='itc_reason',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='gstr2binvoice',
            name='original_no',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='registerinvoice',
            name='itc_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registerinvoice',
            name='itc_reason',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='registerinvoice',
            name='original_no',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
