# Generated by Django 5.2.17 on 2026-10-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0003_portal_itc_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconrun',
            name='register_from_books',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
