# Generated by Django 5.2.6 on 2026-09-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_firm_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamevent',
            name='kind',
            field=models.CharField(choices=[('member.invited', 'Invited'), ('member.joined', 'Joined'), ('invite.revoked', 'Invite revoked'), ('member.role_changed', 'Role changed'), ('firm.owner_changed', 'Ownership transferred'), ('firm.renamed', 'Firm renamed'), ('member.manager_changed', 'Moved to another team'), ('member.scope_changed', 'All-clients access changed'), ('member.deactivated', 'Deactivated'), ('member.removed', 'Removed from firm'), ('member.reactivated', 'Reactivated'), ('client.lead_changed', 'Client lead changed'), ('client.assigned', 'Assigned to client'), ('client.unassigned', 'Removed from client')], max_length=32),
        ),
    ]
