# Generated by Django 5.2.6 on 2026-09-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_row_level_security'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmmembership',
            name='role',
            field=models.CharField(choices=[('FIRM_ADMIN', 'Firm administrator'), ('SENIOR_CA', 'Senior CA'), ('STAFF', 'Staff'), ('READ_ONLY', 'Read only')], default='STAFF', max_length=16),
        ),
    ]
