"""Jobs: work the API reports on rather than blocking for.

Schema only; tenant isolation follows in 0005, separately, for the reason set
out in banking/migrations/0002_row_level_security.py.
"""

# Generated by Django 5.2.6 on 2026-09-12 19:20

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from core.db.rls import ddl_tenant_context_operations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_firmmembership_role'),
    ]

    operations = [
        # First: core_job has foreign keys to core_firm and core_user, and
        # core_firm is behind FORCE ROW LEVEL SECURITY. PostgreSQL validates a
        # new foreign key by scanning both sides, and that scan raises without a
        # tenant context. See core/db/rls.py.
        *ddl_tenant_context_operations(),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('kind', models.CharField(help_text='e.g. statement.ingest', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, max_length=255)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
            ],
            options={
                'db_table': 'core_job',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['firm', 'status'], name='idx_job_firm_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('firm', 'idempotency_key'), name='uniq_job_idempotency_key')],
            },
        ),
    ]
