"""The person behind an account.

Not firm-scoped, and so deliberately without a row-level security policy, for
the same reason ``core_user`` has none: a profile hangs off an account, and an
account is resolved before any firm context exists. ``core.tests.test_rls_isolation``
only demands policies of ``FirmScopedModel`` subclasses, and this is not one.

Two things Django's autogenerated migration would not do:

* **Grant the table to the application role.** Every table in this schema is
  granted explicitly; there is no blanket grant to inherit from, so a new table
  is unreadable by the web role until this runs.
* **Backfill.** The post-save signal in ``core/signals.py`` gives new accounts a
  profile. Accounts that already exist need one too, or the section is empty
  for exactly the people who were here first.
"""

# Generated by Django 5.2.6 on 2026-09-16 20:45

import django.db.models.deletion
import django.utils.timezone
import uuid

from core.db.rls import APP_ROLE
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_one_firm_per_person_and_same_firm_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('display_name', models.CharField(blank=True, help_text="Leave blank to use the account's full name.", max_length=255)),
                ('designation', models.CharField(blank=True, choices=[('PARTNER', 'Partner'), ('CA', 'Chartered Accountant'), ('ARTICLE', 'Article assistant'), ('ACCOUNTANT', 'Accountant'), ('ADMIN', 'Administrator'), ('OTHER', 'Other')], default='', max_length=16)),
                ('icai_membership_no', models.CharField(blank=True, default='', max_length=32, verbose_name='ICAI membership number')),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('avatar_url', models.URLField(blank=True, default='', verbose_name='Avatar URL')),
                ('timezone', models.CharField(default='Asia/Kolkata', help_text='Used when showing this person dates and times.', max_length=64)),
                ('notes', models.TextField(blank=True, default='', help_text='Internal. Visible to the platform owner only.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_profile',
                'ordering': ['user__email'],
            },
        ),
        migrations.RunSQL(
            sql=f"GRANT SELECT, INSERT, UPDATE, DELETE ON core_profile TO {APP_ROLE};",
            reverse_sql=f"REVOKE ALL ON core_profile FROM {APP_ROLE};",
        ),
        migrations.RunSQL(
            sql=(
                "INSERT INTO core_profile (id, created_at, user_id, display_name, "
                "designation, icai_membership_no, phone, avatar_url, timezone, notes) "
                "SELECT gen_random_uuid(), now(), u.id, '', '', '', '', '', "
                "'Asia/Kolkata', '' "
                "FROM core_user u "
                "WHERE NOT EXISTS (SELECT 1 FROM core_profile p WHERE p.user_id = u.id);"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
