# Generated by Django 5.2.6 on 2026-09-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_client_signed_off_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='business_profile',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
