# Generated by Django 5.2.17 on 2026-10-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_audit_log_append_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='close_period',
            field=models.CharField(choices=[('QUARTERLY', 'Quarterly (30 Jun, 30 Sep, 31 Dec, 31 Mar)'), ('HALF_YEARLY', 'Half-yearly (30 Sep, 31 Mar)'), ('YEARLY', 'Yearly (31 Mar)')], db_default='QUARTERLY', default='QUARTERLY', max_length=12),
        ),
    ]
