"""The journal: approved, permanent accounting entries.

Schema only. Isolation and immutability are applied in 0002 -- they have to be a
separate migration, and immutability doubly so: revoking UPDATE on a table
Django is still adding constraints to would fail the migration itself.
"""

# Generated by Django 5.2.6 on 2026-09-12 10:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

from core.db.rls import ddl_tenant_context_operations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0002_row_level_security'),
        ('classify', '0004_vendor_row_level_security'),
        ('core', '0003_alter_firmmembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First, or the foreign key validation scan runs against core_client
        # and banking_statement_transaction with no tenant context and raises.
        # See core/db/rls.py.
        *ddl_tenant_context_operations(),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('entry_no', models.PositiveIntegerField()),
                ('financial_year', models.PositiveSmallIntegerField()),
                ('entry_date', models.DateField()),
                ('voucher_type', models.CharField(choices=[('Payment', 'Payment'), ('Receipt', 'Receipt'), ('Contra', 'Contra'), ('Journal', 'Journal')], max_length=16)),
                ('narration', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField()),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_entries', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='core.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
                ('source_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='banking.statementtransaction')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_set', to='ledger.journalentry')),
            ],
            options={
                'db_table': 'ledger_journal_entry',
                'ordering': ['entry_date', 'entry_no'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('direction', models.CharField(choices=[('DR', 'Debit'), ('CR', 'Credit')], max_length=2)),
                ('amount_paise', models.BigIntegerField()),
                ('signed_paise', models.BigIntegerField()),
                ('rcm', models.BooleanField(default=False)),
                ('tds_section', models.CharField(blank=True, max_length=16)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='ledger.journalentry')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='classify.ledgeraccount')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='classify.vendor')),
            ],
            options={
                'db_table': 'ledger_journal_line',
                'ordering': ['-signed_paise'],
            },
        ),
        migrations.CreateModel(
            name='VoucherSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('financial_year', models.PositiveSmallIntegerField(help_text='Starting year, e.g. 2025.')),
                ('voucher_type', models.CharField(choices=[('Payment', 'Payment'), ('Receipt', 'Receipt'), ('Contra', 'Contra'), ('Journal', 'Journal')], max_length=16)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_sequences', to='core.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
            ],
            options={
                'db_table': 'ledger_voucher_sequence',
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['firm', 'client', 'entry_date'], name='idx_entry_client_date'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('firm', 'client', 'financial_year', 'voucher_type', 'entry_no'), name='uniq_voucher_number_per_book'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['firm', 'ledger_account'], name='idx_line_ledger'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='ck_line_amount_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direction', 'DR'), ('signed_paise__gt', 0)), models.Q(('direction', 'CR'), ('signed_paise__lt', 0)), _connector='OR'), name='ck_line_sign_matches_direction'),
        ),
        migrations.AddConstraint(
            model_name='vouchersequence',
            constraint=models.UniqueConstraint(fields=('firm', 'client', 'financial_year', 'voucher_type'), name='uniq_voucher_sequence'),
        ),
    ]
