"""Tables for the Tally import. Security is in 0010: foreign keys are validated after this
migration's operations, by which time FORCE'd policies would hide the rows.

Additive only: two new tables, nothing the running release reads or writes.
"""

# Generated by Django 5.2.6 on 2026-10-01 18:51

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from core.db.rls import ddl_tenant_context_operations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0017_tally_chart_fields'),
        ('core', '0012_client_business_profile'),
        ('ledger', '0008_mutable_until_signed_off'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First, so the foreign-key scans at the end of this migration can read core_client.
        *ddl_tenant_context_operations(),
        migrations.CreateModel(
            name='LedgerImportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('kind', models.CharField(choices=[('CHART_OPENING', 'Chart of accounts and opening balances')], default='CHART_OPENING', max_length=16)),
                ('financial_year', models.PositiveSmallIntegerField(help_text='Starting year, e.g. 2025.')),
                ('file_sha256', models.CharField(max_length=64)),
                ('source_format', models.CharField(max_length=8)),
                ('include_openings', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PREVIEW', 'Previewed, not applied'), ('CONFIRMED', 'Applied'), ('DISCARDED', 'Discarded')], default='PREVIEW', max_length=12)),
                ('books_from', models.DateField(blank=True, null=True)),
                ('counts', models.JSONField(default=dict)),
                ('rows', models.JSONField(default=list)),
                ('chart_stamp', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('result', models.JSONField(blank=True, default=dict)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_import_runs', to='core.client')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ledger_import_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerOpening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('financial_year', models.PositiveSmallIntegerField(help_text='Starting year, e.g. 2025.')),
                ('signed_paise', models.BigIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_openings', to='core.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='openings', to='classify.ledgeraccount')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openings', to='ledger.ledgerimportrun')),
            ],
            options={
                'db_table': 'ledger_opening',
            },
        ),
        migrations.AddIndex(
            model_name='ledgerimportrun',
            index=models.Index(fields=['firm', 'client', 'created_at'], name='idx_import_run_client'),
        ),
        migrations.AddIndex(
            model_name='ledgeropening',
            index=models.Index(fields=['firm', 'client', 'financial_year'], name='idx_opening_client_year'),
        ),
        migrations.AddConstraint(
            model_name='ledgeropening',
            constraint=models.UniqueConstraint(fields=('firm', 'client', 'ledger', 'financial_year'), name='uniq_opening_per_ledger_year'),
        ),
    ]
