# Generated by Django 5.2.17 on 2026-10-05 11:41

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

from core.db.rls import ddl_tenant_context_operations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0018_party_ledger'),
        ('core', '0012_client_business_profile'),
        ('documents', '0002_row_level_security'),
        ('ledger', '0010_tally_import_security'),
    ]

    operations = [
        # First, so the foreign-key scans at the end of this migration can read the firm-scoped tables.
        *ddl_tenant_context_operations(),
        migrations.AddField(
            model_name='journalentry',
            name='entry_kind',
            field=models.CharField(choices=[('BANK', 'Posted from a bank statement row'), ('VOUCHER', 'A purchase, sales or note voucher'), ('JOURNAL', 'A journal voucher')], db_default='BANK', default='BANK', max_length=8),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='voucher_type',
            field=models.CharField(choices=[('Payment', 'Payment'), ('Receipt', 'Receipt'), ('Contra', 'Contra'), ('Journal', 'Journal'), ('Purchase', 'Purchase'), ('Sales', 'Sales'), ('Debit Note', 'Debit Note'), ('Credit Note', 'Credit Note')], max_length=16),
        ),
        migrations.AlterField(
            model_name='vouchersequence',
            name='voucher_type',
            field=models.CharField(choices=[('Payment', 'Payment'), ('Receipt', 'Receipt'), ('Contra', 'Contra'), ('Journal', 'Journal'), ('Purchase', 'Purchase'), ('Sales', 'Sales'), ('Debit Note', 'Debit Note'), ('Credit Note', 'Credit Note')], max_length=16),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('kind', models.CharField(choices=[('PURCHASE', 'Purchase invoice'), ('SALES', 'Sales invoice'), ('DEBIT_NOTE', 'Debit note (a purchase return)'), ('CREDIT_NOTE', 'Credit note (a sales return)'), ('OPENING', 'Opening balance, as a bill')], max_length=12)),
                ('direction', models.CharField(choices=[('DR', 'Debit'), ('CR', 'Credit')], max_length=2)),
                ('reference', models.CharField(max_length=64)),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('booked_on', models.DateField()),
                ('financial_year', models.PositiveSmallIntegerField()),
                ('taxable_paise', models.BigIntegerField(default=0)),
                ('cgst_paise', models.BigIntegerField(default=0)),
                ('sgst_paise', models.BigIntegerField(default=0)),
                ('igst_paise', models.BigIntegerField(default=0)),
                ('cess_paise', models.BigIntegerField(default=0)),
                ('round_off_paise', models.BigIntegerField(default=0)),
                ('tds_paise', models.BigIntegerField(default=0)),
                ('rcm', models.BooleanField(default=False)),
                ('total_paise', models.BigIntegerField()),
                ('invoice_key', models.CharField(db_index=True, max_length=64)),
                ('own_gstin_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='core.client')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='documents.document')),
                ('entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill', to='ledger.journalentry')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='classify.party')),
            ],
            options={
                'db_table': 'ledger_bill',
                'ordering': ['bill_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('kind', models.CharField(choices=[('AGAINST_BILL', 'Against a bill'), ('ON_ACCOUNT', 'On account'), ('ADVANCE', 'Advance')], max_length=12)),
                ('amount_paise', models.BigIntegerField()),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='ledger.bill')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_allocations', to='core.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='ledger.journalline')),
            ],
            options={
                'db_table': 'ledger_bill_allocation',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['firm', 'client', 'party'], name='idx_bill_party'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['firm', 'client', 'bill_date'], name='idx_bill_date'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['firm', 'own_gstin_hash', 'invoice_key'], name='idx_bill_gst_key'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(fields=('firm', 'client', 'kind', 'financial_year', 'invoice_key'), name='uniq_bill_per_invoice'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(condition=models.Q(('total_paise__gt', 0)), name='ck_bill_total_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(condition=models.Q(('cgst_paise__gte', 0), ('igst_paise__gte', 0), ('sgst_paise__gte', 0), ('taxable_paise__gte', 0), ('cess_paise__gte', 0), ('tds_paise__gte', 0)), name='ck_bill_amounts_are_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direction', 'CR'), ('kind__in', ['PURCHASE', 'CREDIT_NOTE'])), models.Q(('direction', 'DR'), ('kind__in', ['SALES', 'DEBIT_NOTE'])), ('kind', 'OPENING'), _connector='OR'), name='ck_bill_direction_matches_kind'),
        ),
        migrations.AddIndex(
            model_name='billallocation',
            index=models.Index(fields=['firm', 'bill'], name='idx_allocation_bill'),
        ),
        migrations.AddIndex(
            model_name='billallocation',
            index=models.Index(fields=['firm', 'line'], name='idx_allocation_line'),
        ),
        migrations.AddConstraint(
            model_name='billallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='ck_allocation_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='billallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bill__isnull', False), ('kind', 'AGAINST_BILL')), models.Q(models.Q(('kind', 'AGAINST_BILL'), _negated=True), ('bill__isnull', True)), _connector='OR'), name='ck_allocation_bill_matches_kind'),
        ),
    ]
