# Generated by Django 5.2.17 on 2026-10-06 06:09

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from core.db.rls import ddl_tenant_context_operations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_audit_log_append_only'),
        ('documents', '0002_row_level_security'),
        ('ledger', '0013_line_trigger_keeps_the_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First, so the foreign-key scans can read the firm-scoped tables.
        *ddl_tenant_context_operations(),
        migrations.CreateModel(
            name='InvoiceReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('kind', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALES', 'Sales')], max_length=12)),
                ('status', models.CharField(choices=[('OPEN', 'Waiting for a person'), ('BOOKED', 'Booked as a bill'), ('ATTACHED', 'Attached to a bill already booked'), ('DISCARDED', 'Set aside')], default='OPEN', max_length=10)),
                ('proved', models.BooleanField(default=False)),
                ('checks', models.JSONField(default=list)),
                ('unreadable_reason', models.CharField(blank=True, default='', max_length=255)),
                ('payload_enc', models.BinaryField(blank=True, null=True)),
                ('invoice_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('bill', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reading', to='ledger.bill')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_readings', to='core.client')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_readings', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reading', to='documents.document')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
            ],
            options={
                'db_table': 'ledger_invoice_reading',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['firm', 'client', 'status'], name='idx_reading_client_status')],
            },
        ),
    ]
