# Generated by Django 5.2.17 on 2026-10-06 06:59

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from core.db.rls import ddl_tenant_context_operations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_audit_log_append_only'),
        ('ledger', '0015_invoice_readings_security'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        *ddl_tenant_context_operations(),
        migrations.CreateModel(
            name='CloseAcknowledgement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('item_key', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=500)),
                ('acknowledged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='close_acknowledgements', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='close_acknowledgements', to='core.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
            ],
            options={
                'db_table': 'ledger_close_acknowledgement',
                'constraints': [models.UniqueConstraint(fields=('firm', 'client', 'item_key'), name='uniq_close_ack_per_item')],
            },
        ),
    ]
