# Generated by Django 5.2.17 on 2026-10-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0017_close_acknowledgements_security'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksevent',
            name='action',
            field=models.CharField(choices=[('REQUESTED', 'Approval requested'), ('RETURNED', 'Returned for changes'), ('APPROVED', 'Approved by the senior'), ('SIGNED_OFF', 'Sealed'), ('REOPENED', 'Reopened')], max_length=12),
        ),
    ]
