# Generated by Django 5.2.17 on 2026-10-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0018_alter_booksevent_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksevent',
            name='fingerprint',
            field=models.CharField(blank=True, db_default='', default='', max_length=64),
        ),
    ]
