# Generated by Django 5.2.17 on 2026-10-06 11:30

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

from core.db.rls import ddl_tenant_context_operations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0021_classification_bill_status'),
        ('core', '0014_client_close_period'),
        ('ledger', '0019_books_event_fingerprint'),
    ]

    operations = [
        *ddl_tenant_context_operations(),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('cost_paise', models.BigIntegerField()),
                ('residual_paise', models.BigIntegerField(default=0)),
                ('put_to_use', models.DateField()),
                ('method', models.CharField(choices=[('SLM', 'Straight line (Companies Act)'), ('WDV', 'Written-down value, by days in use (Companies Act)'), ('WDV_IT', 'Written-down value, 180-day rule (Income-tax)')], default='SLM', max_length=8)),
                ('life_years', models.PositiveSmallIntegerField(default=0)),
                ('rate_bp', models.PositiveIntegerField(default=0, help_text='Annual rate in basis points: 1500 is 15%.')),
                ('disposed_on', models.DateField(blank=True, null=True)),
                ('disposal_paise', models.BigIntegerField(blank=True, help_text='What it was sold for.', null=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='ledger.bill')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='core.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='classify.ledgeraccount')),
            ],
            options={
                'db_table': 'ledger_fixed_asset',
                'ordering': ['put_to_use', 'name'],
                'indexes': [models.Index(fields=['firm', 'client'], name='idx_asset_client')],
                'constraints': [models.CheckConstraint(condition=models.Q(('cost_paise__gt', 0)), name='ck_asset_cost_positive'), models.CheckConstraint(condition=models.Q(('residual_paise__gte', 0), ('residual_paise__lt', models.F('cost_paise'))), name='ck_asset_residual_below_cost')],
            },
        ),
    ]
