# Generated by Django 5.2.17 on 2026-10-06 13:59

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

from core.db.rls import ddl_tenant_context_operations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_client_close_period'),
        ('ledger', '0021_fixed_assets_security'),
    ]

    operations = [
        *ddl_tenant_context_operations(),
        migrations.CreateModel(
            name='DepreciationPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('financial_year', models.PositiveSmallIntegerField(help_text='Starting year: 2025 is FY 2025-26.')),
                ('total_paise', models.BigIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_postings', to='core.client')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_posting', to='ledger.journalentry')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
            ],
            options={
                'db_table': 'ledger_depreciation_posting',
                'constraints': [models.UniqueConstraint(fields=('firm', 'client', 'financial_year'), name='uniq_depreciation_per_year')],
            },
        ),
    ]
