# Generated by Django 5.2.17 on 2026-10-06 14:11

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

from core.db.rls import ddl_tenant_context_operations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_client_close_period'),
        ('ledger', '0023_depreciation_postings_security'),
    ]

    operations = [
        *ddl_tenant_context_operations(),
        migrations.CreateModel(
            name='TdsChallan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('section', models.CharField(max_length=16)),
                ('bsr_code', models.CharField(max_length=7)),
                ('serial', models.CharField(max_length=5)),
                ('paid_on', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tds_challans', to='core.client')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tds_challan', to='ledger.journalentry')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
            ],
            options={
                'db_table': 'ledger_tds_challan',
                'ordering': ['paid_on'],
                'indexes': [models.Index(fields=['firm', 'client', 'section'], name='idx_tds_challan_section')],
            },
        ),
    ]
