# Generated by Django 5.2.17 on 2026-10-06 15:13

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

from core.db.rls import ddl_tenant_context_operations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0021_classification_bill_status'),
        ('core', '0014_client_close_period'),
        ('ledger', '0025_tds_challans_security'),
    ]

    operations = [
        *ddl_tenant_context_operations(),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
                ('ledger', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_record', to='classify.ledgeraccount')),
            ],
            options={
                'db_table': 'ledger_employee',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('gross_paise', models.BigIntegerField()),
                ('net_paise', models.BigIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='core.client')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_run', to='ledger.journalentry')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
            ],
            options={
                'db_table': 'ledger_payroll_run',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('gross_paise', models.BigIntegerField()),
                ('pf_employee_paise', models.BigIntegerField(default=0)),
                ('pf_employer_paise', models.BigIntegerField(default=0)),
                ('esi_employee_paise', models.BigIntegerField(default=0)),
                ('esi_employer_paise', models.BigIntegerField(default=0)),
                ('tds_paise', models.BigIntegerField(default=0)),
                ('other_deduction_paise', models.BigIntegerField(default=0)),
                ('net_paise', models.BigIntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_lines', to='ledger.employee')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.payrollrun')),
            ],
            options={
                'db_table': 'ledger_payroll_line',
            },
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('firm', 'client', 'name'), name='uniq_employee_name_per_client'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('firm', 'client', 'year', 'month'), name='uniq_payroll_per_month'),
        ),
        migrations.AddConstraint(
            model_name='payrollline',
            constraint=models.UniqueConstraint(fields=('run', 'employee'), name='uniq_payroll_line_per_employee'),
        ),
    ]
