# Generated by Django 5.2.17 on 2026-10-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0027_payroll_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicereading',
            name='attention',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoicereading',
            name='auto_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoicereading',
            name='kind',
            field=models.CharField(blank=True, choices=[('PURCHASE', 'Purchase'), ('SALES', 'Sales')], default='', max_length=12),
        ),
    ]
