# Generated by Django 5.2.17 on 2026-10-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0028_invoice_auto_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrychange',
            name='action',
            field=models.CharField(choices=[('EDITED', 'Ledger changed'), ('REMOVED', 'Entry removed'), ('AI_REVISED', 'Revised by the AI after a correction'), ('RENUMBERED', 'Voucher renumbered at sign-off'), ('RECTIFIED', 'Rectified by a journal after sign-off')], max_length=12),
        ),
    ]
