# Generated by Django 5.2.17 on 2026-10-10 13:17

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from core.db.rls import ddl_tenant_context_operations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_client_nce_settings'),
        ('ledger', '0029_rectified_change_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        *ddl_tenant_context_operations(),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('kind', models.CharField(choices=[('OPENING', 'Opening stock'), ('ADJUSTMENT', 'Stock adjustment')], max_length=12)),
                ('entry_date', models.DateField()),
                ('direction', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=3)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('value_paise', models.BigIntegerField(db_default=0, default=0)),
                ('note', models.CharField(blank=True, db_default='', default='', max_length=300)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='core.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
            ],
            options={
                'db_table': 'ledger_stock_entry',
                'ordering': ['entry_date', 'name'],
                'indexes': [models.Index(fields=['firm', 'client', 'entry_date'], name='idx_stock_entry_client_date')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_stock_quantity_positive'), models.CheckConstraint(condition=models.Q(('value_paise__gte', 0)), name='ck_stock_value_not_negative')],
            },
        ),
    ]
