# Generated by Django 5.2.17 on 2026-10-10 15:13

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

from core.db.rls import ddl_tenant_context_operations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0023_msme_and_note_section'),
        ('core', '0015_client_nce_settings'),
        ('ledger', '0031_stock_entries_security'),
    ]

    operations = [
        *ddl_tenant_context_operations(),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, db_default='', default='', max_length=16)),
                ('hsn_sac', models.CharField(blank=True, db_default='', default='', max_length=8)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='core.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
                ('purchase_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='classify.ledgeraccount')),
                ('sales_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='classify.ledgeraccount')),
            ],
            options={
                'db_table': 'ledger_stock_item',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('firm', 'client', 'name'), name='uniq_stock_item_name')],
            },
        ),
    ]
