# Generated by Django 5.2.17 on 2026-10-06 20:19

import django.utils.timezone
import uuid
from django.db import migrations, models

from core.db.rls import APP_ROLE


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # The role the grant below names is created by core's first migrations.
        ('core', '0014_client_close_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('purpose', models.CharField(choices=[('CLASSIFY', 'Placing bank rows in ledgers'), ('SCAN', 'Reading a scanned statement'), ('OTHER', 'Other')], max_length=12)),
                ('model', models.CharField(blank=True, default='', max_length=80)),
                ('outcome', models.CharField(choices=[('OK', 'Answered'), ('RATE_LIMITED', 'Rate limited'), ('ERROR', 'Failed')], default='OK', max_length=14)),
                ('firm_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('client_id', models.UUIDField(blank=True, null=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('cached_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('rows', models.PositiveIntegerField(default=0)),
                ('pages', models.PositiveIntegerField(default=0)),
                ('cost_micro_usd', models.BigIntegerField(default=0)),
                ('priced', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'model call',
                'verbose_name_plural': 'model calls',
                'db_table': 'usage_event',
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['firm_id', 'at'], name='idx_usage_firm_at')],
            },
        ),
        # The web role may add a call and read them, and nothing else: no update, no delete, so a recorded call cannot be
        # rewritten from the application. The table has no row-level security on purpose (it holds platform operating
        # figures, never a firm's data), so what it holds is counts and tokens only.
        migrations.RunSQL(
            sql=f"GRANT SELECT, INSERT ON usage_event TO {APP_ROLE};",
            reverse_sql=f"REVOKE ALL ON usage_event FROM {APP_ROLE};",
        ),
    ]
