# Generated by Django 5.2.6 on 2026-09-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0005_platform_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAuditLog',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('firm_name', models.CharField(max_length=255, null=True, verbose_name='firm')),
                ('user_email', models.EmailField(max_length=254, null=True, verbose_name='user')),
                ('method', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=512)),
                ('status_code', models.PositiveSmallIntegerField(verbose_name='status')),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='IP address')),
                ('request_id', models.CharField(max_length=64)),
                ('duration_ms', models.PositiveIntegerField(null=True, verbose_name='ms')),
                ('created_at', models.DateTimeField(verbose_name='when')),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit logs',
                'db_table': 'app"."platform_audit_log',
                'ordering': ['-created_at'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformClient',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('firm_name', models.CharField(max_length=255, verbose_name='firm')),
                ('name', models.CharField(max_length=255)),
                ('fy_start', models.DateField(verbose_name='financial year starts')),
                ('lead_email', models.EmailField(max_length=254, null=True, verbose_name='lead')),
                ('created_at', models.DateTimeField()),
                ('team_size', models.IntegerField(verbose_name='assigned')),
                ('bank_account_count', models.IntegerField(verbose_name='bank accounts')),
                ('statement_count', models.IntegerField(verbose_name='statements')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'db_table': 'app"."platform_clients',
                'ordering': ['firm_name', 'name'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformClientAssignment',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255, verbose_name='client')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'app"."platform_client_assignments',
                'ordering': ['client_name'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformFirm',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('member_count', models.IntegerField(verbose_name='people')),
                ('client_count', models.IntegerField(verbose_name='clients')),
            ],
            options={
                'verbose_name': 'firm',
                'verbose_name_plural': 'firms',
                'db_table': 'app"."platform_firms',
                'ordering': ['name'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformJob',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('firm_name', models.CharField(max_length=255, verbose_name='firm')),
                ('kind', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], max_length=16)),
                ('progress', models.PositiveSmallIntegerField()),
                ('message', models.CharField(max_length=255)),
                ('error_code', models.CharField(max_length=64)),
                ('created_by_email', models.EmailField(max_length=254, null=True, verbose_name='started by')),
                ('created_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
                'db_table': 'app"."platform_jobs',
                'ordering': ['-created_at'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformMembership',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('firm_name', models.CharField(max_length=255, verbose_name='firm')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255, verbose_name='name')),
                ('role', models.CharField(choices=[('FIRM_ADMIN', 'Firm administrator'), ('SENIOR_CA', 'Senior CA'), ('STAFF', 'Staff'), ('READ_ONLY', 'Read only')], max_length=16)),
                ('is_active', models.BooleanField(verbose_name='active')),
                ('is_owner', models.BooleanField(verbose_name='owner')),
                ('scope_all_clients', models.BooleanField(verbose_name='sees all clients')),
                ('manager_id', models.UUIDField(null=True)),
                ('manager_email', models.EmailField(max_length=254, null=True, verbose_name='reports to')),
                ('created_at', models.DateTimeField(verbose_name='joined')),
            ],
            options={
                'verbose_name': 'firm membership',
                'verbose_name_plural': 'firm memberships',
                'db_table': 'app"."platform_memberships',
                'ordering': ['firm_name', 'email'],
                'abstract': False,
                'managed': False,
            },
        ),
    ]
