"""Bank accounts, statements, and the rows read out of them.

Schema only. Tenant isolation is applied in 0002, and has to be separate --
see the note there.
"""

# Generated by Django 5.2.6 on 2026-09-12 10:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models

from core.db.rls import ddl_tenant_context_operations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_firmmembership_role'),
        ('documents', '0001_initial'),
    ]

    operations = [
        # Must be first. These tables carry foreign keys to core_client and
        # core_firm, which are already behind FORCE ROW LEVEL SECURITY, and
        # PostgreSQL's foreign key validation scan reads the referenced table.
        # Without a tenant context that scan raises and takes the migration with
        # it. See core/db/rls.py.
        *ddl_tenant_context_operations(),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('bank_code', models.CharField(help_text='Parser identifier, e.g. AXIS.', max_length=16)),
                ('account_number_enc', models.BinaryField()),
                ('account_number_hash', models.CharField(db_index=True, max_length=64)),
                ('account_last4', models.CharField(blank=True, max_length=4)),
                ('account_holder_enc', models.BinaryField(blank=True, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=16)),
                ('ledger_name', models.CharField(blank=True, max_length=255)),
                ('opening_balance_paise', models.BigIntegerField(blank=True, null=True)),
                ('opening_as_of', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='core.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
            ],
            options={
                'db_table': 'banking_bank_account',
                'ordering': ['bank_code', 'account_last4'],
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('opening_balance_paise', models.BigIntegerField()),
                ('closing_balance_paise', models.BigIntegerField()),
                ('total_debit_paise', models.BigIntegerField()),
                ('total_credit_paise', models.BigIntegerField()),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('parser', models.CharField(blank=True, max_length=64)),
                ('parser_version', models.PositiveIntegerField(default=1)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='banking.bankaccount')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statement', to='documents.document')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
            ],
            options={
                'db_table': 'banking_statement',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatementTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('row_number', models.PositiveIntegerField(help_text='1-based position within the statement.')),
                ('value_date', models.DateField()),
                ('narration', models.TextField(help_text="The bank's particulars, line wrapping removed.")),
                ('cheque_number', models.CharField(blank=True, max_length=32)),
                ('debit_paise', models.BigIntegerField(default=0)),
                ('credit_paise', models.BigIntegerField(default=0)),
                ('balance_paise', models.BigIntegerField()),
                ('branch_code', models.CharField(blank=True, max_length=16)),
                ('dedupe_hash', models.CharField(max_length=64)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankaccount')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.statement')),
            ],
            options={
                'db_table': 'banking_statement_transaction',
                'ordering': ['value_date', 'row_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('firm', 'client', 'bank_code', 'account_number_hash'), name='uniq_bank_account_per_client'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('opening_as_of__isnull', True), ('opening_balance_paise__isnull', True)), models.Q(('opening_as_of__isnull', False), ('opening_balance_paise__isnull', False)), _connector='OR'), name='ck_opening_balance_has_a_date'),
        ),
        migrations.AddIndex(
            model_name='statement',
            index=models.Index(fields=['firm', 'bank_account', 'period_start'], name='idx_stmt_account_period'),
        ),
        migrations.AddIndex(
            model_name='statementtransaction',
            index=models.Index(fields=['firm', 'bank_account', 'value_date'], name='idx_txn_account_date'),
        ),
        migrations.AddConstraint(
            model_name='statementtransaction',
            constraint=models.UniqueConstraint(fields=('firm', 'statement', 'row_number'), name='uniq_transaction_row_per_statement'),
        ),
        migrations.AddConstraint(
            model_name='statementtransaction',
            constraint=models.UniqueConstraint(fields=('firm', 'bank_account', 'dedupe_hash'), name='uniq_transaction_per_account'),
        ),
        migrations.AddConstraint(
            model_name='statementtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('debit_paise__gte', 0), ('credit_paise__gte', 0)), name='ck_transaction_amounts_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='statementtransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit_paise__gt', 0), ('credit_paise', 0)), models.Q(('debit_paise', 0), ('credit_paise__gt', 0)), _connector='OR'), name='ck_transaction_is_one_sided'),
        ),
    ]
