# Generated by Django 5.2.6 on 2026-09-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_row_level_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_holder',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
