# Generated by Django 5.2.17 on 2026-10-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_bankaccount_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='kind',
            field=models.CharField(choices=[('BANK', 'Bank account'), ('LOAN', 'Loan account'), ('CARD', 'Credit card')], db_default='BANK', default='BANK', max_length=8),
        ),
    ]
