"""The upload registry. Schema only; RLS follows in 0002."""

# Generated by Django 5.2.6 on 2026-09-12 10:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

from core.db.rls import ddl_tenant_context_operations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_firmmembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Must be first. These tables carry foreign keys to core_client and
        # core_firm, which are already behind FORCE ROW LEVEL SECURITY, and
        # PostgreSQL's foreign key validation scan reads the referenced table.
        # Without a tenant context that scan raises and takes the migration with
        # it. See core/db/rls.py.
        *ddl_tenant_context_operations(),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('kind', models.CharField(choices=[('BANK_STATEMENT', 'Bank statement'), ('PURCHASE_INVOICE', 'Purchase invoice'), ('SALES_INVOICE', 'Sales invoice'), ('GSTR2B', 'GSTR-2B extract'), ('REGISTER', 'Purchase or sales register'), ('TALLY_EXPORT', 'Tally export'), ('OTHER', 'Other')], max_length=24)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('storage_key', models.CharField(blank=True, max_length=512)),
                ('byte_size', models.PositiveBigIntegerField(default=0)),
                ('page_count', models.PositiveSmallIntegerField(default=0)),
                ('pipeline_tier', models.CharField(choices=[('UNKNOWN', 'Not yet routed'), ('TEXT_LAYER', 'Born-digital text layer'), ('OCR', 'Optical character recognition'), ('MANUAL', 'Keyed in by hand')], default='UNKNOWN', max_length=16)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PARSED', 'Parsed'), ('FAILED', 'Could not be read')], default='RECEIVED', max_length=16)),
                ('failure_reason', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_document',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['firm', 'client', 'kind'], name='idx_document_client_kind')],
                'constraints': [models.UniqueConstraint(fields=('firm', 'sha256'), name='uniq_document_per_firm_sha256')],
            },
        ),
    ]
