# Generated by Django 5.2.17 on 2026-10-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_row_level_security'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pipeline_tier',
            field=models.CharField(choices=[('UNKNOWN', 'Not yet routed'), ('TEXT_LAYER', 'Born-digital text layer'), ('OCR', 'Optical character recognition'), ('VISION', 'Read from page images by a vision model'), ('MANUAL', 'Keyed in by hand')], default='UNKNOWN', max_length=16),
        ),
    ]
