# Generated by Django 5.2.17 on 2026-10-07 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_client_close_period'),
        ('documents', '0003_pipeline_tier_vision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='uniq_document_per_firm_sha256',
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('firm', 'client', 'sha256'), name='uniq_document_per_client_sha256'),
        ),
    ]
