"""Ledgers, classification rules, and per-transaction results.

Schema only; tenant isolation follows in 0002.
"""

# Generated by Django 5.2.6 on 2026-09-12 10:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

from core.db.rls import ddl_tenant_context_operations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
        ('core', '0003_alter_firmmembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Must be first. These tables carry foreign keys to core_client and
        # core_firm, which are already behind FORCE ROW LEVEL SECURITY, and
        # PostgreSQL's foreign key validation scan reads the referenced table.
        # Without a tenant context that scan raises and takes the migration with
        # it. See core/db/rls.py.
        *ddl_tenant_context_operations(),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(choices=[('BANK', 'Bank Accounts'), ('CASH', 'Cash-in-Hand'), ('DEBTOR', 'Sundry Debtors'), ('CREDITOR', 'Sundry Creditors'), ('INDIRECT_EXPENSE', 'Indirect Expenses'), ('DIRECT_EXPENSE', 'Direct Expenses'), ('INDIRECT_INCOME', 'Indirect Incomes'), ('DIRECT_INCOME', 'Direct Incomes'), ('DUTIES_AND_TAXES', 'Duties & Taxes'), ('LOAN', 'Loans (Liability)'), ('INVESTMENT', 'Investments'), ('CAPITAL', 'Capital Account'), ('SUSPENSE', 'Suspense A/c')], default='SUSPENSE', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='core.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
            ],
            options={
                'db_table': 'classify_ledger_account',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('match_type', models.CharField(choices=[('PARTY_EQUALS', 'Counterparty is exactly'), ('PARTY_CONTAINS', 'Counterparty contains'), ('NARRATION_CONTAINS', 'Narration contains'), ('CHANNEL_IS', 'Channel is'), ('REGEX', 'Narration matches regular expression')], default='PARTY_EQUALS', max_length=24)),
                ('pattern', models.CharField(max_length=255)),
                ('direction', models.CharField(choices=[('ANY', 'Either'), ('DEBIT', 'Money out'), ('CREDIT', 'Money in')], default='ANY', max_length=8)),
                ('priority', models.IntegerField(default=100)),
                ('source', models.CharField(choices=[('SEED', 'Built in'), ('LEARNED', 'Learned from a review'), ('MANUAL', 'Written by hand')], default='LEARNED', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('last_hit_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classification_rules', to='core.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classification_rules', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='classify.ledgeraccount')),
            ],
            options={
                'db_table': 'classify_rule',
                'ordering': ['-priority', 'pattern'],
            },
        ),
        migrations.CreateModel(
            name='TransactionClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('method', models.CharField(choices=[('RULE', 'Matched a rule'), ('UNRESOLVED', 'Awaiting review'), ('REVIEWED', 'Set by a person'), ('LLM', 'Suggested by a language model')], default='UNRESOLVED', max_length=16)),
                ('confidence', models.FloatField(default=0.0)),
                ('needs_review', models.BooleanField(default=True)),
                ('channel', models.CharField(blank=True, max_length=16)),
                ('counterparty', models.CharField(blank=True, max_length=255)),
                ('is_self_transfer', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classifications', to='classify.ledgeraccount')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifications', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifications', to='classify.classificationrule')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='banking.statementtransaction')),
            ],
            options={
                'db_table': 'classify_transaction_classification',
            },
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(fields=('firm', 'client', 'name'), name='uniq_ledger_name_per_client'),
        ),
        migrations.AddIndex(
            model_name='classificationrule',
            index=models.Index(fields=['firm', 'client', 'is_active'], name='idx_rule_client_active'),
        ),
        migrations.AddConstraint(
            model_name='classificationrule',
            constraint=models.UniqueConstraint(fields=('firm', 'client', 'match_type', 'pattern', 'direction'), name='uniq_rule_per_client_pattern'),
        ),
        migrations.AddIndex(
            model_name='transactionclassification',
            index=models.Index(fields=['firm', 'needs_review'], name='idx_classification_queue'),
        ),
        migrations.AddConstraint(
            model_name='transactionclassification',
            constraint=models.UniqueConstraint(fields=('firm', 'transaction'), name='uniq_classification_per_transaction'),
        ),
        migrations.AddConstraint(
            model_name='transactionclassification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ledger__isnull', True), ('method', 'UNRESOLVED')), models.Q(models.Q(('method', 'UNRESOLVED'), _negated=True), ('ledger__isnull', False)), _connector='OR'), name='ck_unresolved_has_no_ledger'),
        ),
    ]
