"""Vendors, tax treatment, and confidence bands.

Adds the party dimension the requirements document calls for -- a ledger head
alone is not usable output -- along with the reverse-charge and TDS flags that
ride with it, and the confidence the review screen sorts by.
"""

# Generated by Django 5.2.6 on 2026-09-12 10:38

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

from core.db.rls import ddl_tenant_context_operations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0002_row_level_security'),
        ('core', '0003_alter_firmmembership_role'),
    ]

    operations = [
        # classify_vendor takes a foreign key to core_client, which is behind
        # FORCE ROW LEVEL SECURITY. PostgreSQL validates that key by scanning
        # both tables, and without a tenant context the scan raises. See
        # core/db/rls.py.
        *ddl_tenant_context_operations(),
        migrations.AddField(
            model_name='classificationrule',
            name='confidence',
            field=models.FloatField(default=0.9),
        ),
        migrations.AddField(
            model_name='classificationrule',
            name='rcm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classificationrule',
            name='tds_section',
            field=models.CharField(blank=True, choices=[('192', '192 -- Salary'), ('194A', '194A -- Interest other than securities'), ('194C', '194C -- Payment to contractors'), ('194H', '194H -- Commission or brokerage'), ('194I', '194I -- Rent'), ('194J', '194J -- Professional or technical fees'), ('194Q', '194Q -- Purchase of goods')], max_length=16),
        ),
        migrations.AddField(
            model_name='transactionclassification',
            name='rcm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactionclassification',
            name='review_band',
            field=models.CharField(choices=[('HIGH', 'High confidence -- bulk approvable'), ('ADVISED', 'Review advised'), ('JUDGEMENT', 'Needs human judgement')], default='JUDGEMENT', max_length=12),
        ),
        migrations.AddField(
            model_name='transactionclassification',
            name='tds_section',
            field=models.CharField(blank=True, choices=[('192', '192 -- Salary'), ('194A', '194A -- Interest other than securities'), ('194C', '194C -- Payment to contractors'), ('194H', '194H -- Commission or brokerage'), ('194I', '194I -- Rent'), ('194J', '194J -- Professional or technical fees'), ('194Q', '194Q -- Purchase of goods')], max_length=16),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('canonical_name', models.CharField(max_length=255)),
                ('alias_token', models.CharField(db_index=True, max_length=24)),
                ('gstin_enc', models.BinaryField(blank=True, null=True)),
                ('gstin_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('rcm_default', models.BooleanField(default=False)),
                ('tds_section', models.CharField(blank=True, choices=[('192', '192 -- Salary'), ('194A', '194A -- Interest other than securities'), ('194C', '194C -- Payment to contractors'), ('194H', '194H -- Commission or brokerage'), ('194I', '194I -- Rent'), ('194J', '194J -- Professional or technical fees'), ('194Q', '194Q -- Purchase of goods')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='core.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.firm')),
            ],
            options={
                'db_table': 'classify_vendor',
                'ordering': ['canonical_name'],
            },
        ),
        migrations.AddField(
            model_name='classificationrule',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='classify.vendor'),
        ),
        migrations.AddField(
            model_name='transactionclassification',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifications', to='classify.vendor'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('firm', 'client', 'canonical_name'), name='uniq_vendor_name_per_client'),
        ),
    ]
