# Generated by Django 5.2.6 on 2026-09-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0013_party_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionclassification',
            name='ai_revised',
            field=models.BooleanField(default=False),
        ),
    ]
