# Generated by Django 5.2.6 on 2026-10-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0016_model_attempts_db_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeraccount',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='tally_group_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='tally_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ledgeraccount',
            name='group',
            field=models.CharField(choices=[('BANK', 'Bank Accounts'), ('CASH', 'Cash-in-Hand'), ('DEBTOR', 'Sundry Debtors'), ('CREDITOR', 'Sundry Creditors'), ('INDIRECT_EXPENSE', 'Indirect Expenses'), ('DIRECT_EXPENSE', 'Direct Expenses'), ('INDIRECT_INCOME', 'Indirect Incomes'), ('DIRECT_INCOME', 'Direct Incomes'), ('DUTIES_AND_TAXES', 'Duties & Taxes'), ('LOAN', 'Loans (Liability)'), ('INVESTMENT', 'Investments'), ('CAPITAL', 'Capital Account'), ('SUSPENSE', 'Suspense A/c'), ('FIXED_ASSET', 'Fixed Assets'), ('STOCK', 'Stock-in-Hand'), ('CURRENT_ASSET', 'Current Assets'), ('LOAN_ADVANCE', 'Loans & Advances (Asset)'), ('DEPOSIT', 'Deposits (Asset)'), ('MISC_EXPENDITURE', 'Misc. Expenses (Asset)'), ('BANK_OD', 'Bank OD A/c'), ('CURRENT_LIABILITY', 'Current Liabilities'), ('PROVISION', 'Provisions'), ('RESERVES', 'Reserves & Surplus'), ('SALES', 'Sales Accounts'), ('PURCHASE', 'Purchase Accounts')], default='SUSPENSE', max_length=32),
        ),
    ]
