# Generated by Django 5.2.17 on 2026-10-05 11:40

import django.db.models.deletion
from django.db import migrations, models

from core.db.rls import ddl_tenant_context_operations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0017_tally_chart_fields'),
    ]

    operations = [
        # First, so the foreign-key scans at the end of this migration can read the firm-scoped tables.
        *ddl_tenant_context_operations(),
        migrations.AddField(
            model_name='party',
            name='ledger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='party_record', to='classify.ledgeraccount'),
        ),
    ]
