# Generated by Django 5.2.17 on 2026-10-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0020_classification_trigger_keeps_the_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionclassification',
            name='bill_status',
            field=models.CharField(blank=True, choices=[('', 'Not said'), ('NO_INVOICE_EXPECTED', 'No invoice expected (a direct expense)'), ('NEEDS_INVOICE', 'Needs an invoice')], db_default='', default='', max_length=24),
        ),
    ]
