# Generated by Django 5.2.17 on 2026-10-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0021_classification_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeraccount',
            name='nce_line',
            field=models.CharField(blank=True, db_default='', default='', max_length=16),
        ),
    ]
