/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppFirmRouteImport } from './routes/_app/firm'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppWorkRouteImport } from './routes/_app/work'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppClientsIndexRouteImport } from './routes/_app/clients/index'
import { Route as AppClientsClientIdRouteRouteImport } from './routes/_app/clients/$clientId/route'
import { Route as AppClientsClientIdIndexRouteImport } from './routes/_app/clients/$clientId/index'
import { Route as AppClientsClientIdBooksRouteImport } from './routes/_app/clients/$clientId/books'
import { Route as AppClientsClientIdDaybookRouteImport } from './routes/_app/clients/$clientId/daybook'
import { Route as AppClientsClientIdMastersRouteImport } from './routes/_app/clients/$clientId/masters'
import { Route as AppClientsClientIdReportsRouteImport } from './routes/_app/clients/$clientId/reports'
import { Route as AppClientsClientIdReviewRouteImport } from './routes/_app/clients/$clientId/review'
import { Route as AppClientsClientIdStatementsRouteImport } from './routes/_app/clients/$clientId/statements'
import { Route as AppClientsClientIdTeamRouteImport } from './routes/_app/clients/$clientId/team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFirmRoute = AppFirmRouteImport.update({
  id: '/firm',
  path: '/firm',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkRoute = AppWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AppRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsClientIdRouteRoute = AppClientsClientIdRouteRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsClientIdIndexRoute = AppClientsClientIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClientsClientIdRouteRoute,
} as any)
const AppClientsClientIdBooksRoute = AppClientsClientIdBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AppClientsClientIdRouteRoute,
} as any)
const AppClientsClientIdDaybookRoute =
  AppClientsClientIdDaybookRouteImport.update({
    id: '/daybook',
    path: '/daybook',
    getParentRoute: () => AppClientsClientIdRouteRoute,
  } as any)
const AppClientsClientIdMastersRoute =
  AppClientsClientIdMastersRouteImport.update({
    id: '/masters',
    path: '/masters',
    getParentRoute: () => AppClientsClientIdRouteRoute,
  } as any)
const AppClientsClientIdReportsRoute =
  AppClientsClientIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AppClientsClientIdRouteRoute,
  } as any)
const AppClientsClientIdReviewRoute =
  AppClientsClientIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AppClientsClientIdRouteRoute,
  } as any)
const AppClientsClientIdStatementsRoute =
  AppClientsClientIdStatementsRouteImport.update({
    id: '/statements',
    path: '/statements',
    getParentRoute: () => AppClientsClientIdRouteRoute,
  } as any)
const AppClientsClientIdTeamRoute = AppClientsClientIdTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppClientsClientIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/firm': typeof AppFirmRoute
  '/team': typeof AppTeamRoute
  '/work': typeof AppWorkRoute
  '/invite/$token': typeof InviteTokenRoute
  '/clients/$clientId': typeof AppClientsClientIdRouteRouteWithChildren
  '/clients/': typeof AppClientsIndexRoute
  '/clients/$clientId/books': typeof AppClientsClientIdBooksRoute
  '/clients/$clientId/daybook': typeof AppClientsClientIdDaybookRoute
  '/clients/$clientId/masters': typeof AppClientsClientIdMastersRoute
  '/clients/$clientId/reports': typeof AppClientsClientIdReportsRoute
  '/clients/$clientId/review': typeof AppClientsClientIdReviewRoute
  '/clients/$clientId/statements': typeof AppClientsClientIdStatementsRoute
  '/clients/$clientId/team': typeof AppClientsClientIdTeamRoute
  '/clients/$clientId/': typeof AppClientsClientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/firm': typeof AppFirmRoute
  '/team': typeof AppTeamRoute
  '/work': typeof AppWorkRoute
  '/invite/$token': typeof InviteTokenRoute
  '/clients': typeof AppClientsIndexRoute
  '/clients/$clientId/books': typeof AppClientsClientIdBooksRoute
  '/clients/$clientId/daybook': typeof AppClientsClientIdDaybookRoute
  '/clients/$clientId/masters': typeof AppClientsClientIdMastersRoute
  '/clients/$clientId/reports': typeof AppClientsClientIdReportsRoute
  '/clients/$clientId/review': typeof AppClientsClientIdReviewRoute
  '/clients/$clientId/statements': typeof AppClientsClientIdStatementsRoute
  '/clients/$clientId/team': typeof AppClientsClientIdTeamRoute
  '/clients/$clientId': typeof AppClientsClientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/firm': typeof AppFirmRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/work': typeof AppWorkRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_app/clients/$clientId': typeof AppClientsClientIdRouteRouteWithChildren
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/clients/$clientId/books': typeof AppClientsClientIdBooksRoute
  '/_app/clients/$clientId/daybook': typeof AppClientsClientIdDaybookRoute
  '/_app/clients/$clientId/masters': typeof AppClientsClientIdMastersRoute
  '/_app/clients/$clientId/reports': typeof AppClientsClientIdReportsRoute
  '/_app/clients/$clientId/review': typeof AppClientsClientIdReviewRoute
  '/_app/clients/$clientId/statements': typeof AppClientsClientIdStatementsRoute
  '/_app/clients/$clientId/team': typeof AppClientsClientIdTeamRoute
  '/_app/clients/$clientId/': typeof AppClientsClientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/firm'
    | '/team'
    | '/work'
    | '/invite/$token'
    | '/clients/$clientId'
    | '/clients/'
    | '/clients/$clientId/books'
    | '/clients/$clientId/daybook'
    | '/clients/$clientId/masters'
    | '/clients/$clientId/reports'
    | '/clients/$clientId/review'
    | '/clients/$clientId/statements'
    | '/clients/$clientId/team'
    | '/clients/$clientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/firm'
    | '/team'
    | '/work'
    | '/invite/$token'
    | '/clients'
    | '/clients/$clientId/books'
    | '/clients/$clientId/daybook'
    | '/clients/$clientId/masters'
    | '/clients/$clientId/reports'
    | '/clients/$clientId/review'
    | '/clients/$clientId/statements'
    | '/clients/$clientId/team'
    | '/clients/$clientId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/firm'
    | '/_app/team'
    | '/_app/work'
    | '/invite/$token'
    | '/_app/clients/$clientId'
    | '/_app/clients/'
    | '/_app/clients/$clientId/books'
    | '/_app/clients/$clientId/daybook'
    | '/_app/clients/$clientId/masters'
    | '/_app/clients/$clientId/reports'
    | '/_app/clients/$clientId/review'
    | '/_app/clients/$clientId/statements'
    | '/_app/clients/$clientId/team'
    | '/_app/clients/$clientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/firm': {
      id: '/_app/firm'
      path: '/firm'
      fullPath: '/firm'
      preLoaderRoute: typeof AppFirmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/work': {
      id: '/_app/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof AppWorkRouteImport
      parentRoute: typeof AppRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$clientId': {
      id: '/_app/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AppClientsClientIdRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$clientId/': {
      id: '/_app/clients/$clientId/'
      path: '/'
      fullPath: '/clients/$clientId/'
      preLoaderRoute: typeof AppClientsClientIdIndexRouteImport
      parentRoute: typeof AppClientsClientIdRouteRoute
    }
    '/_app/clients/$clientId/books': {
      id: '/_app/clients/$clientId/books'
      path: '/books'
      fullPath: '/clients/$clientId/books'
      preLoaderRoute: typeof AppClientsClientIdBooksRouteImport
      parentRoute: typeof AppClientsClientIdRouteRoute
    }
    '/_app/clients/$clientId/daybook': {
      id: '/_app/clients/$clientId/daybook'
      path: '/daybook'
      fullPath: '/clients/$clientId/daybook'
      preLoaderRoute: typeof AppClientsClientIdDaybookRouteImport
      parentRoute: typeof AppClientsClientIdRouteRoute
    }
    '/_app/clients/$clientId/masters': {
      id: '/_app/clients/$clientId/masters'
      path: '/masters'
      fullPath: '/clients/$clientId/masters'
      preLoaderRoute: typeof AppClientsClientIdMastersRouteImport
      parentRoute: typeof AppClientsClientIdRouteRoute
    }
    '/_app/clients/$clientId/reports': {
      id: '/_app/clients/$clientId/reports'
      path: '/reports'
      fullPath: '/clients/$clientId/reports'
      preLoaderRoute: typeof AppClientsClientIdReportsRouteImport
      parentRoute: typeof AppClientsClientIdRouteRoute
    }
    '/_app/clients/$clientId/review': {
      id: '/_app/clients/$clientId/review'
      path: '/review'
      fullPath: '/clients/$clientId/review'
      preLoaderRoute: typeof AppClientsClientIdReviewRouteImport
      parentRoute: typeof AppClientsClientIdRouteRoute
    }
    '/_app/clients/$clientId/statements': {
      id: '/_app/clients/$clientId/statements'
      path: '/statements'
      fullPath: '/clients/$clientId/statements'
      preLoaderRoute: typeof AppClientsClientIdStatementsRouteImport
      parentRoute: typeof AppClientsClientIdRouteRoute
    }
    '/_app/clients/$clientId/team': {
      id: '/_app/clients/$clientId/team'
      path: '/team'
      fullPath: '/clients/$clientId/team'
      preLoaderRoute: typeof AppClientsClientIdTeamRouteImport
      parentRoute: typeof AppClientsClientIdRouteRoute
    }
  }
}

interface AppClientsClientIdRouteRouteChildren {
  AppClientsClientIdBooksRoute: typeof AppClientsClientIdBooksRoute
  AppClientsClientIdDaybookRoute: typeof AppClientsClientIdDaybookRoute
  AppClientsClientIdMastersRoute: typeof AppClientsClientIdMastersRoute
  AppClientsClientIdReportsRoute: typeof AppClientsClientIdReportsRoute
  AppClientsClientIdReviewRoute: typeof AppClientsClientIdReviewRoute
  AppClientsClientIdStatementsRoute: typeof AppClientsClientIdStatementsRoute
  AppClientsClientIdTeamRoute: typeof AppClientsClientIdTeamRoute
  AppClientsClientIdIndexRoute: typeof AppClientsClientIdIndexRoute
}

const AppClientsClientIdRouteRouteChildren: AppClientsClientIdRouteRouteChildren =
  {
    AppClientsClientIdBooksRoute: AppClientsClientIdBooksRoute,
    AppClientsClientIdDaybookRoute: AppClientsClientIdDaybookRoute,
    AppClientsClientIdMastersRoute: AppClientsClientIdMastersRoute,
    AppClientsClientIdReportsRoute: AppClientsClientIdReportsRoute,
    AppClientsClientIdReviewRoute: AppClientsClientIdReviewRoute,
    AppClientsClientIdStatementsRoute: AppClientsClientIdStatementsRoute,
    AppClientsClientIdTeamRoute: AppClientsClientIdTeamRoute,
    AppClientsClientIdIndexRoute: AppClientsClientIdIndexRoute,
  }

const AppClientsClientIdRouteRouteWithChildren =
  AppClientsClientIdRouteRoute._addFileChildren(
    AppClientsClientIdRouteRouteChildren,
  )

interface AppRouteChildren {
  AppFirmRoute: typeof AppFirmRoute
  AppTeamRoute: typeof AppTeamRoute
  AppWorkRoute: typeof AppWorkRoute
  AppClientsClientIdRouteRoute: typeof AppClientsClientIdRouteRouteWithChildren
  AppClientsIndexRoute: typeof AppClientsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFirmRoute: AppFirmRoute,
  AppTeamRoute: AppTeamRoute,
  AppWorkRoute: AppWorkRoute,
  AppClientsClientIdRouteRoute: AppClientsClientIdRouteRouteWithChildren,
  AppClientsIndexRoute: AppClientsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
